# Generated by Django 4.1.13 on 2024-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='code',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
