# Generated by Django 4.1.13 on 2024-04-12 06:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_test_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('branchName', models.CharField(max_length=200)),
                ('branchCity', models.CharField(max_length=200)),
                ('details', tinymce.models.HTMLField()),
                ('contact', tinymce.models.HTMLField()),
                ('timeZone', models.CharField(max_length=50)),
                ('coordinates', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
